# DynamicBan 1.3.0b - Comprehensive Administration System. 
config:
    check_for_updates: true
    # Do you want to check for updates?
    plugin_tag: '&0[&3DynamicBan&0]&f: '
    # How do you want the plugin messages to be tagged? ('' to deactivate)
    broadcast_on_kick: true
    # Do you want to broadcast kicks?
    broadcast_on_ban: true
    # Do you want to broadcast bans?
    broadcast_on_ipban: true
    # Do you want to broadcast ipbans?
    broadcast_on_tempban: true
    # Do you want to broadcast tempbans?
    broadcast_on_iptempban: true
    # Do you want to broadcast iptempbans?
    broadcast_on_same_ip: true
    # Do you want to broadcast when two players have the same ip?
    broadcast_on_mute: true
    # Do you want to broadcast mutes?
    broadcast_on_unmute: false
    # Do you want to broadcast unmutes?
    broadcast_on_warn: true
    # Do you want to broadcast warnings?
    broadcast_on_rangeban: true
    # Do you want to broadcast rangebans?
    broadcast_on_unban: false
    # Do you want to broadcast unbans?
    warns_timeout: 72
    # How many hours do you want to keep warnings? (0 to keep warnings permanently)
    warns_on_login: true
    # Should players be informed about their warnings after they logged in?
    warns_on_login_delay: 0
    # By how many seconds should the warning notification be delayed? (0 to deactivate)
    connections_per_ip: 5
    # How many connections do you want to allow per ip? (0 to deactivate)
    messages_per_ip: 3
    # For how many connections from the same ip should the join and leave message be shown? (0 to deactivate)
    op_immune_bypass: false
    # Allows OPs to bypass the immunity of players.
    mute:
        blocked_commands:
        # When a player is muted, what commands should be disallowed?
            - msg
            - tell
            - r
            - er
    dnsbl_services:
        - zen.spamhaus.org
        - dnsbl.sorbs.net
    # Which DNSBL services do you want to be checked?
    dnsbl_result: none
    # What should happen when a blacklisted ip attempts to join? (none, kick, ban, ipban, notify)
messages:
    # Variables are {SENDER}, {REASON} and {TIME} for temporary actions
    kick_message: "You have been kicked. Reason: {REASON}"
    # The kick message.
    mute_message: "&cYou have been muted by {SENDER}. Time left: {TIME}"
    # The mute message.
    unmute_message: "&bYou have been unmuted by {SENDER}."
    # The unmute message.
    ban_message: "You have been banned. Reason: {REASON}"
    # The ban message.
    tempban_message: "You have been temporarily banned. Time left: {TIME}"
    # The tempban message.
    ip_tempban_message: "You have been temporarily ip-banned. Time left: {TIME}"
    # The tempipban message.
    ip_ban_message: "Your IP has been banned. Reason: {REASON}"
    # The ipban message.
    warn_kick_message: "You were kicked after multiple warnings."
    # The warnkick message.
    locked_ip_message: "That IP has been locked to another player."
    # The iplock message.
    ip_connections_message: "Too many players connected from your IP."
    # The iplimit message.
    rangeban_message: "Your IP-range has been banned. Reason: {REASON}"
    # The rangeban message.
    muted_message: "&cYou cannot talk, you have been muted. Time left: {TIME}"
    # The message to send to the player when he/she is muted and attempts to send a message.
    muted_command_blocked: "&cYou cannot perform that command, you have been muted! Time left: {TIME}"
    # The message to send to the player when he/she is muted and attempts a blocked command.
broadcast_messages:
    # Variables are {PLAYER}, {SENDER}, {REASON} and {TIME} for temporary actions
    kick_message: "&b{PLAYER} has been kicked. Reason: {REASON}"
    # The broadcast message when a player is kicked.
    mute_message: "&b{PLAYER} has been muted. Time: {TIME}"
    # The broadcast message when a player is muted.
    unmute_message: "&b{PLAYER}'s mute has been removed."
    # The broadcast message when a player is muted.
    ban_message: "&b{PLAYER} has been banned. Reason: {REASON}"
    # The broadcast message when a player is banned.
    tempban_message: "&b{PLAYER} has been temporarily banned. Time: {TIME}"
    # The broadcast message when a player is tempbanned.
    ip_tempban_message: "&b{PLAYER} has been temporarily ip-banned. Time: {TIME}"
    # The broadcast message when a player is iptempbanned.
    ip_ban_message: "&b{PLAYER} has been ip-banned. Reason: {REASON}"
    # The broadcast message when a player is ipbanned.
    warn_message: "&b{PLAYER} has recieved a warning. Reason: {REASON}."
    # The broadcast message when a player is warned.
    rangeban_message: "&b{PLAYER} has been range-banned. Reason: {REASON}"
    # The broadcast message when a player is rangebanned.
    unban_message: "&b{PLAYER}'s ban has been removed."
    # The broadcast message when a player is unbanned.
other_messages:
    immune_message: "&cThat player is immune to your command!"
    # The message the commandsender will recieve if a player is immune.
    warned_message: "&c{SENDER} warned you. Reason: {REASON}."
    # The message to send to the player when he/she is warned.
    same_ip_message: "&b{PLAYER} logged in on the same IP ({IP}) as {OLDERPLAYER}."
    # The message to send to players with permission/op when the are two or more players with the same ip.
    dnsbl_ip_message: "&b{PLAYER}'s ip is blacklisted."
    warnings_message: "&cYou have been warned for the following reason(s):&b{WARNS}&cYou have {AMOUNT} warning(s)."
    # The message to send to players if warns_on_login is true. Each warning will be sent in a new line.
    default_reason: "&cUnspecified"
    # The default reason for everything.
    dnsbl_reason: "&cYour ip is blacklisted."
    # The default reason for DNSBL bans.
    